src/main/java/com/onedrinktoday/backend/domain/member/controller/MemberController.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java, src/main/java/com/onedrinktoday/backend/global/security/JwtProvider.java, src/main/java/com/onedrinktoday/backend/global/security/TokenDTO.java
**AS-IS**
* domain 패키지:
* 엑세스 토큰 만료 시 리프레시 토큰을 통해 새로운 엑세스 토큰을 발급받는 기능을 구현
* global 패키지
* ErrorCode파일에서 JWT를 사용하는 인증 시스템에 관한 토큰 관련 문제 에러 코드 생성
---
- 응답 형식을 문자열 대신 JSON 형태의 Map으로 구성하여 사용자에게 제공하도록 하였습니다.
---
**TO-BE**
- 액세스 토큰 갱신 가능
=> feat: JWT 리프레시 토큰 메커니즘 구현

src/main/java/com/onedrinktoday/backend/global/config/SecurityConfig.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java, src/main/java/com/onedrinktoday/backend/global/security/GoogleController.java, src/main/java/com/onedrinktoday/backend/global/security/GoogleService.java, src/main/java/com/onedrinktoday/backend/global/security/JwtFilter.java, src/main/java/com/onedrinktoday/backend/global/security/MemberDetail.java, src/main/java/com/onedrinktoday/backend/global/security/MemberDetailService.java
**AS-IS**
* 구글 로그인/회원가입 기능 구현
* 프론트에서 요청시 구글 로그인 페이지 uri 넘겨주는 컨트롤러 생성
* 프론트에서 Auth Code 넘겨받고 Access Token 교환 -> 유저 정보 받아오기
* DB에 가입된 이메일이 있으면 로그인 처리, 없으면 회원가입+로그인 동시 처리
* 구글에서 받아오는 정보는 이름(닉네임), 이메일 -> 나머지 회원정보(주종, 지역 등)는 빈 상태로 회원가입됨
-> 회원가입후 마이페이지에서 설정 필요
* UserDetail 관련 클래스 생성 -> 백엔드 서버 접근시 JWT 필터에서 정보 확인후 Authentication 저장
**TO-BE**
* 현준님이 PR 하신 부분(TokenDTO 로 반환)은 아직 적용하지 못했습니다. 한번 머지후 반영해서 다시 PR 올리도록 하겠습니다.
* 프론트 분들께서 Auth Code 리다이렉션 받을 프론트 서버의 uri 주시면 반영 예정
=> feat: 구글 로그인 기능 구현

build.gradle, src/main/java/com/onedrinktoday/backend/domain/member/controller/MemberController.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/ChangePasswordRequestDTO.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/PasswordResetDTO.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/PasswordResetRequest.java, src/main/java/com/onedrinktoday/backend/domain/member/service/EmailService.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java
**AS-IS**
- 비밀번호 재설정 기능 추가
- 비밀번호 재설정 요청 : 사용자가 이메일 제출하면, 해당 이메일을 찾고 비밀번호 재설정 토큰을 생성하여 이메일로 전송
- JwtProvider에서 비밀번호 재설정 토큰 기한 설정 및 토큰 생성 메서드 추가
- MemberService의 requestPasswordReset 메서드 통해, JwtProvider에서 생성한 토큰을 사용하여 비밀번호 재설정 링크가 이메일로 발송
- EmailService의 sendPasswordResetEmail 메서드 통해, 이메일 발송 처리
- 비밀번호 재설정 처리
- 사용자가 이메일로 받은 링크에서 토큰을 포함해 비밀번호 재설정하는 API 추가
- 해당 API는 토큰의 유효성 검증 후, 새로운 비밀번호로 사용자 계정의 비밀번호를 업데이트 
- 비밀번호 재설정 요청 `/members/request-password-reset` : 사용자가 이메일을 입력하면 비밀번호 재설정 링크 발송
- 비밀번호 재설정 `/members/reset-password` : 사용자가 재설정 페이지에서 새로운 비밀번호를 입력하면, 해당 비밀번호로 계정 업데이트
=> feat: 비밀번호 재설정 기능 구현

src/test/java/com/onedrinktoday/backend/domain/member/service/RegionServiceTest.java
- 지역 저장 성공: 사용자가 새로운 지역을 성공적으로 저장할 수 있는지 확인
- 지역 저장 실패: 용자가 이미 존재하는 지역명을 저장하려 할 때, 실패하는지 확인
- 모든 지역 조회: 성공: 모든 지역을 조회할 수 있는지 확인
- 모든 지역 조회: 실패: 지역 조회 중 오류가 발생할 때, 실패하는지 확인
- 지역 조회 성공: 특정 지역 ID로 단일 지역 정보를 성공적으로 조회할 수 있는지 확인
- 지역 조회 실패: 존재하지 않는 지역 ID로 조회할 때, 실패하는지 확인
=> test: RegionServiceTest 테스트 코드 작성

src/test/java/com/onedrinktoday/backend/domain/member/controller/MemberControllerTest.java
- 회원가입 성공: 요청이 성공적으로 처리되고, 반환된 값이 올바른지 확
- 회원가입 실패: 필수 입력 정보가 누락된 회원가입 요청 시 400 Bad Request와 함께 MEMBER_INFORMATION_MISSING 오류가 반환되는지 확인
- 로그인 성공: 올바른 이메일과 비밀번호로 요청이 성공적으로 처리되고, 토큰이 반환되는지 확
- 로그인 실패: 잘못된 이메일 또는 비밀번호로 로그인 요청 시 400 Bad Request와 LOGIN_FAIL 오류가 반환되는지 테스트합니다.
- 비밀번호 재설정 요청 성공: 유효한 이메일로 요청이 성공적으로 처리되는지 확인
- 비밀번호 재설정 요청 실패: 등록되지 않은 이메일로 요청 시 400 Bad Request와 EMAIL_NOT_FOUND 오류가 반환되는지 확인
- 비밀번호 재설정 페이지 리디렉션 성공: 유효한 토큰으로 비밀번호 재설정 페이지가 성공적으로 리디렉션되는지 확인
- 비밀번호 재설정 페이지 리디렉션 실패: 토큰 없이 요청 시 400 Bad Request되는지 확인
- 비밀번호 재설정 성공 (비밀번호 모를 경우): 유효한 토큰과 새 비밀번호로 요청이 성공적으로 처리되는지 확인
- 비밀번호 재설정 실패 (비밀번호 모를 경우): 유효하지 않은 토큰으로 요청 시 400 Bad Request와 INVALID_REFRESH_TOKEN 오류가 반환되는지 확인
- 비밀번호 변경 성공 (비밀번호 알고 있을 경우): 현재 비밀번호와 새 비밀번호로 요청이 성공적으로 처리되는지 확인
- 비밀번호 변경 성공 (비밀번호 알고 있을 경우): 잘못된 현재 비밀번호로 요청 시 400 …
=> test: MemberController 테스트 구현

src/main/java/com/onedrinktoday/backend/domain/drink/dto/DrinkDTO.java, src/main/java/com/onedrinktoday/backend/domain/drink/entity/Drink.java, src/main/java/com/onedrinktoday/backend/domain/drink/repository/DrinkRepository.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/domain/post/controller/PostController.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostRequest.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostResponse.java, src/main/java/com/onedrinktoday/backend/domain/post/entity/Post.java, src/main/java/com/onedrinktoday/backend/domain/post/repository/PostRepository.java, src/main/java/com/onedrinktoday/backend/domain/post/service/PostService.java, src/main/java/com/onedrinktoday/backend/domain/postTag/entity/PostTag.java, src/main/java/com/onedrinktoday/backend/domain/postTag/repository/PostTagRepository.java, src/main/java/com/onedrinktoday/backend/domain/tag/dto/TagDTO.java, src/main/java/com/onedrinktoday/backend/domain/tag/entity/Tag.java, src/main/java/com/onedrinktoday/backend/domain/tag/repository/TagRepository.java, src/main/java/com/onedrinktoday/backend/global/security/GoogleService.java, src/main/java/com/onedrinktoday/backend/global/security/JwtProvider.java, src/main/java/com/onedrinktoday/backend/global/type/Type.java, src/test/java/com/onedrinktoday/backend/global/security/GoogleServiceTest.java
**AS-IS**
- 게시글 등록 기능 구현
- 게시글 CRUD 기능 구현을 위해 연관된 Drink, Tag, PostTag 패키지를 추가하였고, 엔티티, 레포지토리, DTO 작성
- 게시글 타입(광고, 리뷰) ENUM 작성
- 게시글 생성 시 이미 등록된 특산주(Drink)를 사용하거나, 새로운 특산주 정보를 함께 입력 가능하도록 구현
- 게시글에 태그(Tag)를 추가할 수 있도록 Tag 및 PostTag 엔티티 작성
- 게시글 작성 후 태그를 PostTag 엔티티를 통해 연결하여 저장하는 로직 구현
- 게시글 생성 시 기본적인 검증 로직 추가(유효한 사용자와 특산주 여부 검증)
- 새로 등록된 음료 정보는 Drink 테이블에 저장되며, 게시글 작성 시 해당 음료 정보와 연관됨
- 게시글 조회 기능 구현
- (GET /api/posts), 모든 게시글을 반환하며, 연관된 특산주 정보와 태그 정보도 포함
- 특정 게시글 조회 기능 구현 -> (GET /api/posts/{postId}), 게시글 ID로 조회 가능하며 연관된 데이터 반환
- 게시글 수정 기능 구현
- (PUT /api/posts/{postId}), 기존 게시글을 수정할 수 있으며, 특산주 및 태그 정보도 업데이트 가능 
- 게시글 삭제 기능 구현
- (DELETE /api/posts/{postId}), soft delete 방식으로 삭제 처리되어 DB에서 즉시 삭제되지 않도록 구현 
TO-BE
- 각 기능 구현에 따른 테스트 코드 작성 예정
=> feat: 게시글 기능 구현

src/main/java/com/onedrinktoday/backend/domain/tagFollow/controller/TagFollowController.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/dto/TagFollowRequest.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/dto/TagFollowResponse.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/entity/TagFollow.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/repository/TagFollowRepository.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/service/TagFollowService.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java, src/test/java/com/onedrinktoday/backend/domain/tagFollow/controller/TagFollowControllerTest.java, src/test/java/com/onedrinktoday/backend/domain/tagFollow/service/TagFollowServiceTest.java
- 태그 팔로우: 사용자가 태그를 팔로우할 수 있도록 followTag 메서드를 구현하였으며, 이미 팔로우 중인 경우에는 ALREADY_FOLLOWING 오류를 반환합니다.
- 태그 팔로우 목록 조회: 사용자가 자신의 팔로우 목록을 조회할 수 있도록 getTagFollows 메서드를 구현하였습니다.
- 태그 팔로우 취소: 사용자가 팔로우한 태그를 취소할 수 있도록 deleteTagFollow 메서드를 구현하였습니다.
=> feat: Tag Follow 기능 구현

src/main/java/com/onedrinktoday/backend/domain/member/controller/MemberController.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/MemberRequest.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/MemberResponse.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostResponse.java, src/main/java/com/onedrinktoday/backend/domain/post/entity/Post.java, src/test/java/com/onedrinktoday/backend/domain/member/controller/MemberRegistrationControllerTest.java, src/test/java/com/onedrinktoday/backend/domain/member/service/MemberRigistrationServiceTest.java
- 이메일 중복 사전 체크 기능
- 가입 시 거주지 받지 않도록
- UpdateInfo: imageUrl 인자로 받지 않도록(파일로 전달받아 백에서 저장 및 url 생성)
- 게시글 imageUrl 필드 추가
=> 이메일 사전 중복 체크, 거주지 정보 삭제, 게시글 imageUrl 필드 추가

src/main/java/com/onedrinktoday/backend/domain/comment/service/CommentService.java, src/main/java/com/onedrinktoday/backend/domain/manager/service/ManagerService.java, src/main/java/com/onedrinktoday/backend/domain/notification/controller/NotificationController.java, src/main/java/com/onedrinktoday/backend/domain/notification/dto/NotificationResponse.java, src/main/java/com/onedrinktoday/backend/domain/notification/entity/Notification.java, src/main/java/com/onedrinktoday/backend/domain/notification/repository/NotificationRepository.java, src/main/java/com/onedrinktoday/backend/domain/notification/service/NotificationService.java, src/main/java/com/onedrinktoday/backend/domain/post/service/PostService.java, src/main/java/com/onedrinktoday/backend/domain/registration/service/RegistrationService.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/repository/TagFollowRepository.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/service/TagFollowService.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java, src/main/java/com/onedrinktoday/backend/global/type/NotificationType.java
- FOLLOW
- 사용자가 팔로우 한 태그를 사용해서 다른 사용자가 게시글을 업로드하면 알림을 생성합니다.
- 알림 생성 시 postId는 팔로우 한 태그의 게시글 ID가 반환됩니다.
- COMMENT
- 게시글에 댓글이 달릴 때 알림을 생성합니다.
- 댓글 작성자가 익명인 경우와 아닐 경우에 따라 알림 메시지가 다르게 설정됩니다.
- 알림의 postId는 댓글이 달린 게시글 ID를 반환합니다.
- REGISTRATION
- 특산주 신청이 승인되었을 때, 신청자에게 승인 알림을 생성합니다.
- 알림 생성 시 postId는 특산주 신청 ID가 반환됩니다.
- DECLARATION, REMOVED
- 게시글이 신고되어 매니저에 의해 삭제된 경우, 게시글 작성자와 신고자에게 알림을 생성합니다.
- 게시글 작성자에게는 "게시글이 신고되어 삭제되었습니다."
- 신고자에게는 "신고한 게시글이 승인되어 삭제되었습니다."
- 신고가 승인된 게시글은 삭제되어 postId는 null이 됩니다.
- 알림 조회 기준
- 최신 알람 기준 20개씩 항목을 반환하도록 설정
- 2명의 사용자와 매니저의 3개의 역할을 위해 3번 회원가입하고 로그인을 진행하여 API테스트를 진행하였습니다.
- 다른 사용자가 팔로우한 태그 게시글 업로드와 특산주 요청 역할 회원
- 댓글 작성, 태그 팔로우와 게시글 신고 역할 회원
- 매니저 역할 회원
=> feat: 5가지 타입의 알림 기능 구현

src/main/java/com/onedrinktoday/backend/domain/drink/dto/DrinkResponse.java, src/main/java/com/onedrinktoday/backend/domain/manager/service/ManagerService.java, src/main/java/com/onedrinktoday/backend/domain/post/controller/PostController.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostRequest.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostResponse.java, src/main/java/com/onedrinktoday/backend/domain/post/repository/PostRepository.java, src/main/java/com/onedrinktoday/backend/domain/post/service/PostService.java, src/main/java/com/onedrinktoday/backend/domain/postTag/entity/PostTag.java, src/main/java/com/onedrinktoday/backend/domain/registration/service/RegistrationService.java, src/main/java/com/onedrinktoday/backend/global/cache/CacheService.java, src/main/java/com/onedrinktoday/backend/global/exception/CustomExceptionHandler.java, src/test/java/com/onedrinktoday/backend/domain/post/controller/PostControllerTest.java, src/test/java/com/onedrinktoday/backend/domain/post/service/PostServiceTest.java
- master 브랜치 충돌 rebase 병합 
- Post(게시글) 평점 기존 Float 타입에서 AVG() 함수 사용으로 형 변환 프로세스를 없애기 위해 Double 타입으로 변경 
- Post(게시글) 전체 게시글 최신순 / 조회수 정렬 조회 기능 구현
- Post(게시글) 이미지 업로드 시 우선순위(1순위 : 게시글 업로드 이미지, 2순위 : 특산주 기본 이미지) 기능 구현 
- PostService 테스트 코드 작성 
- `successCreatePost` - 게시글 생성 성공 테스트
- `memberService.getMember()`를 통해서 사용자 정보를 가져오고, 각 태그와 생성된 게시글 내용 확인, 태그 관련 알림 서비스가 잘 호출되는지 검증
- `failNoDrinkIdCreatePost` - 게시글 생성 실패 테스트
- 잘못된 음료 ID 999L을 설정하고, `drinkRepository.findById(999L)`이 빈 값을 반환하도록 설정, IllegalArgumentException 예외가 발생하는지 확인하여 음료가 없을 경우 적절히 예외 처리가 되는지 검증
- `successGetPostById` - 게시글 조회 성공 테스트
- `postRepository.findById(1L)`와 게시글에 연결된 태그 정보를 설정하고, 음료에 대한 평균 평점을 캐시에서 가져옴. `postService.getPostById(1L)` 메서드를 호출하여 게시글 조회
- `getPostByIdFail` - 게시글 조회 실패 테스트
- 잘못된 게시글 ID 999L에 대해 …
=> refactor: 게시글 미 기능 구현 및 리팩토링, 테스트 코드 구현

src/main/java/com/onedrinktoday/backend/domain/comment/dto/CommentResponse.java, src/main/java/com/onedrinktoday/backend/domain/comment/entity/Comment.java, src/main/java/com/onedrinktoday/backend/domain/comment/repository/CommentRepository.java, src/main/java/com/onedrinktoday/backend/domain/member/controller/MemberController.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/domain/post/dto/PostResponse.java, src/main/java/com/onedrinktoday/backend/domain/post/repository/PostRepository.java, src/main/java/com/onedrinktoday/backend/domain/registration/dto/RegistrationResponse.java, src/main/java/com/onedrinktoday/backend/domain/registration/repository/RegistrationRepository.java, src/main/java/com/onedrinktoday/backend/domain/tagFollow/repository/TagFollowRepository.java, src/test/java/com/onedrinktoday/backend/domain/member/controller/MemberRegistrationControllerTest.java, src/test/java/com/onedrinktoday/backend/domain/member/service/MemberRigistrationServiceTest.java
- 사용자 회원탈퇴 기능 구현
- MemberController
- 회원탈퇴 기능을 처리하는 API를 추가하였습니다.
- 사용자가 회원탈퇴 요청 시, 인증된 사용자를 찾아서 탈퇴를 처리합니다.
- MemberService
- 현재 로그인한 사용자를 인증 정보로 가져와 해당 사용자의 이메일을 사용해 데이터베이스에서 회원 정보를 조회합니다.
- 회원 정보를 조회한 후, 해당 회원이 작성한 게시글, 댓글, 등록 정보를 가져와서 연관된 사용자 정보를 null로 설정하고 저장합니다.
- 회원 정보는 deletedAt 필드가 설정되어 탈퇴 상태로 표시되며, 실제 데이터베이스에서는 삭제되지 않고 비활성화됩니다.
- 회원이 작성한 게시글의 작성자는 "탈퇴한 사용자"로 표시됩니다.
- 탈퇴한 사용자의 게시글에 있는 댓글은 삭제되지 않고, 탈퇴한 댓글의 작성자 정보는 "탈퇴한 사용자"로 변경되며, memberId는 null로 설정됩니다.
- tagFollowRepository를 사용하여 태그 팔로우 정보도 삭제합니다.
- **PostResponse**: 작성자가 탈퇴한 경우 "탈퇴한 사용자"으로 표시 되고 memberId는 null됩니다. 탈퇴한 사용자의 게시글에 있는 댓글은 삭제되지 않습니다. 
- **CommentResponse**: 작성자가 탈퇴한 경우 "탈퇴한 사용자"으로 표시됩니다. 익명여부와 상관없이 탈퇴를 한다면 "탈퇴한 사용자"로 변경되고 memberId는 null이 됩니다.
- **RegistrationResponse**: 작성자가 탈퇴한 경우 사용자 이름은 "탈퇴한 사용자" 그리고 memberId는 …
=> feat: 회원탈퇴 기능 구현

src/main/java/com/onedrinktoday/backend/domain/registration/service/RegistrationService.java
- ManagerService와 동일한 코드로 인하여 매니저가 특산주를 승인하면 사용자에게 두번 알림이 가게 되는 문제가 발생했습니다.
- RegistrationService에 있는 알림 코드 제거를 하여 매니저가 승인을 하면 신청 회원에게 알림을 한번만 호출되도록 수정
=> refactor: 특산주 승인 알림 중복 호출 제거

build.gradle, src/main/java/com/onedrinktoday/backend/domain/autoComplete/AutoCompleteController.java, src/main/java/com/onedrinktoday/backend/domain/autoComplete/AutoCompleteService.java, src/main/java/com/onedrinktoday/backend/domain/manager/service/ManagerService.java, src/main/java/com/onedrinktoday/backend/domain/post/service/PostService.java, src/main/java/com/onedrinktoday/backend/domain/search/ElasticSearchRepository.java, src/main/java/com/onedrinktoday/backend/domain/search/PostDocument.java, src/main/java/com/onedrinktoday/backend/domain/search/SearchController.java, src/main/java/com/onedrinktoday/backend/domain/search/SearchService.java, src/main/java/com/onedrinktoday/backend/global/config/ElasticSearchConfig.java, src/main/resources/elasticsearch/mappings/mappings.json, src/main/resources/elasticsearch/settings/settings.json, src/test/java/com/onedrinktoday/backend/domain/search/SearchServiceTest.java
* 검색 기능
* PostDocument: ES 에 저장될 게시글에 대한 도큐먼트(태그, 특산주 이름 필드를 가짐)
* 게시글 저장, 수정, 삭제시 ES 에 도큐먼트 생성, 수정, 삭제 연동
* 태그/특산주 검색어를 통해 ES 에서 관련 도큐먼트 가져오기 -> Post -> PostResponse 변환과정 거쳐 반환
* 검색의 효율성을 위해 ES 연동시 태그/특산주 이름에서 공백 제거후 저장하고(실제 "서울 특산주" -> ES 저장시 "서울특산주")
검색시에도 검색창에 입력한 단어에 공백 제거후 실제 검색 진행 
* 공백을 제외한 태그/특산주 이름이 정확히 일치하는 게시글만 반환
* 자동완성 기능
* Redis Sorted Set 을 이용해 구현
* 태그, 특산주 등록시 Redis Sorted Set 에 해당 문자열의 substring 저장 -> Redis 에서 사전순으로 자동 정렬된다.
(달콤한 태그 등록시 -> '달', "달콤', '달콤한' 3가지를 redis 에 저장)
* 실제 테이블에 존재하는 태그나 특산주만 반환하기 위해 완전한 단어 뒤에는 * 붙임('달', '달콤', '달콤한*')
* 검색창을 통해 넘어온 검색어의 일부를 넘겨받아 해당 단어로 시작하며, 뒤에 * 가 붙은 문자열 리스트 반환
* 테스트
* ES, Redis 연동해야 적절히 확인 가능한 기능으로 SearchService.save() 만 테스트 구현
* ES 서버 실행후 테스트해 주세요.
* ES 관련 yml 파일 수정 있습니다.
=> feat: 게시글 검색, 자동완성 기능

src/main/java/com/onedrinktoday/backend/domain/announcement/controller/AnnouncementController.java, src/main/java/com/onedrinktoday/backend/domain/announcement/dto/AnnouncementRequest.java, src/main/java/com/onedrinktoday/backend/domain/announcement/dto/AnnouncementResponse.java, src/main/java/com/onedrinktoday/backend/domain/announcement/entity/Announcement.java, src/main/java/com/onedrinktoday/backend/domain/announcement/repository/AnnouncementRepository.java, src/main/java/com/onedrinktoday/backend/domain/announcement/service/AnnouncementService.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java, src/test/java/com/onedrinktoday/backend/domain/announcement/controller/AnnouncementControllerTest.java, src/test/java/com/onedrinktoday/backend/domain/announcement/service/AnnouncementServiceTest.java
- Request에 3개의 필드가 다 @Setter이 필요하여 클래스에 붙였습니다.
- Controller
- 공지사항 생성: 관리자가 새로운 공지사항을 작성할 수 있습니다. 작성자는 AnnouncementRequest를 통해 제목, 내용, 이미지 URL을 입력하여 저장합니다.
- 공지사항 조회: 모든 사용자가 공지사항 목록을 최신순으로 조회할 수 있습니다. 또한, 특정 공지사항을 ID로 조회하는 기능을 추가하였습니다.
- 공지사항 수정: 관리자가 기존 공지사항을 수정할 수 있습니다. 인증된 관리자가 작성자와 일치할 경우에만 수정이 가능하며, 수정된 내용은 AnnouncementRequest를 통해 처리됩니다.
- 공지사항 삭제: 관리자가 특정 공지사항을 삭제할 수 있습니다. 인증된 관리자가 작성자와 일치할 경우에만 삭제가 가능합니다.
- Service
- 공지사항 생성
- memberService.getMember()를 통해 현재 로그인한 사용자 정보를 가져옵니다.
- 공지사항의 제목, 내용을 포함한 새로운 공지사항을 생성합니다.
- 생성된 공지사항을 데이터베이스에 저장하고, 그 정보를 AnnouncementResponse 형태로 반환합니다.
- 전체 공지사항 조회
- 페이지네이션을 지원하여, Pageable을 사용해 요청된 페이지의 공지사항 목록을 가져옵니다.
- 공지사항이 없을 경우, 빈 페이지를 반환합니다.
- 조회된 공지사항 목록을 AnnouncementResponse로 변환하여 반환합니다.
- 단일 공지사항 조회
- 공지사항 ID를 기준으로 공지사항을 조회합니다.
- 공지사항이 존재하지 않을 …
=> feat: 공지사항 기능 구현

src/main/java/com/onedrinktoday/backend/domain/manager/controller/ManagerController.java, src/main/java/com/onedrinktoday/backend/domain/manager/dto/cancelDeclarationRequest.java, src/main/java/com/onedrinktoday/backend/domain/manager/service/ManagerService.java, src/main/java/com/onedrinktoday/backend/domain/notification/service/NotificationService.java, src/main/java/com/onedrinktoday/backend/global/type/NotificationType.java, src/main/java/com/onedrinktoday/backend/global/type/cancelDeclarationType.java, src/test/java/com/onedrinktoday/backend/domain/notification/service/NotificationServiceTest.java
- **NotificationType**: 열거형에 사용자가 신고를 반려할 때 사용하는 타입으로 `REJECTION`을 추가하였습니다.
- **cancelDeclarationType**: 매니저가 `select`할 수 있도록 열거형 신고 취소 사유를 작성하였습니다.
- **cancelDeclarationRequest**: 신고 반려 시 `cancelDeclarationType `중 하나를 선택하여 반려 할 수 있도록 `DTO`를 작성하였습니다.
- **Manager Controller & Service**
- Controller: `@RequestBody cancelDeclarationRequest`가 추가되어, 클라이언트로부터 신고 취소 사유를 담고 있는 열거형 타입을 받을 수 있게 하여 반려 사유를 명확하게 전달할 수 있습니다.
- Service: 입력한 `cancelDeclarationRequest`를 알림 메서드의 인자로 전달하여 알림을 생성하도록 합니다.
- **NotificationService**: 
- `cancelDeclarationRequest`의 `type`에서 해당 사유의 메시지를 가져와, 사용자에게 전송할 알림 메시지를 작성합니다.
-  작성된 메시지와 함께 신고한 회원에게 `REJECTION `타입의 알림을 생성합니다. 이때, 알림은 해당 회원의 ID와 신고 ID를 포함합니다.
- **NotificationServiceTest**: 신고 반려 알림 생성 로직이 올바르게 작동하는지 확인하여, 올바른 알림이 생성되도록 테스트 하였습니다.
=> feat: 신고 반려 기능 구현

build.gradle, src/main/java/com/onedrinktoday/backend/domain/aws/S3Controller.java, src/main/java/com/onedrinktoday/backend/domain/aws/S3Service.java, src/main/java/com/onedrinktoday/backend/domain/member/controller/MemberController.java, src/main/java/com/onedrinktoday/backend/domain/member/dto/UpdateProfileRequest.java, src/main/java/com/onedrinktoday/backend/domain/member/entity/Member.java, src/main/java/com/onedrinktoday/backend/domain/member/service/MemberService.java, src/main/java/com/onedrinktoday/backend/domain/registration/controller/RegistrationController.java, src/main/java/com/onedrinktoday/backend/domain/registration/dto/RegistrationRequest.java, src/main/java/com/onedrinktoday/backend/domain/registration/entity/Registration.java, src/main/java/com/onedrinktoday/backend/global/config/S3Config.java, src/main/java/com/onedrinktoday/backend/global/exception/ErrorCode.java
* 이미지 업로드, url 반환(S3Controller, S3Service)
* 프론트에서 multipartFile 넘겨줌 -> 백엔드에서 받아서 S3 업로드후 url 반환
* 프론트는 받은 url 로 미리보기 표시 가능, 최종 확인버튼 클릭 시 url을 다시 백엔드로 넘겨줘서 DB 에 저장
* 멤버 프로필 이미지
* 회원가입시 이미지 업로드X, 마이페이지에서 변경 가능
* 게시글 이미지
* 게시글 작성시 PostRequest 통해 imageUrl 받기(이미지 올릴때 S3 저장후 프론트에 보내준 url 다시 받는것)
* 게시글 url 비어있을때는 drink 의 url 을 post-imageUrl 로 세팅
* 특산주 이미지
* 필수로 지정 필요(없으면 에러)
* 특산주 등록 신청시 이미지 저장후 url 저장
* 매니저 승인시 신청 테이블 url 을 그대로 특산주 테이블 url 로 복사
* 테스트를 위해 s3 세팅을 직접 다 하기 번거로울것 같아서 제 aws 시크릿키를 포함한 yml을 디스코드로 공유하겠습니다.
* 프론트와 연동해야 적절한 테스트가 이루어질것 같아서 우선 전달받은 url 로 DB 변경하는 부분만 테스트 완료했습니다.
=> 멤버, 특산주, 게시글 이미지 업로드

src/main/java/com/onedrinktoday/backend/domain/suggest/controller/SuggestController.java, src/main/java/com/onedrinktoday/backend/domain/suggest/service/SuggestService.java, src/test/java/com/onedrinktoday/backend/domain/suggest/SuggestServiceTest.java
- 사용자 위치 기반 가장 가까운 지역 특산주 추천
- `suggestDrinkByLocation(Long memberId, Float latitude, Float longitude)` : latitude(위도)와 longitude(경도)를 입력받아, 사용자의 현재 위치를 기반으로 가장 가까운 지역을 찾아 특산주를 추천하는 메서드
- 해당 지역의 특산주 리스트에서 랜덤으로 하나 선택해 반환
- 사용자의 Member 엔티티의 region_id(거주지) 값을 업데이트하여, 이후 동일한 지역의 특산주를 계속 추천받을 수 있도록 처리
- 사용자가 다시 홈 화면 접속시 이미 저장된 사용자의 거주지 위치값을 기반으로 특산주를 보여줌
- `suggestDrinkForCurrentRegion(Long memberId)` : 사용자의 region_id 값을 기반으로 현재 설정된 지역의 특산주를 추천하는 메서드
- 만약, 사용자가 위치 갱신 버튼을 클릭하지 않은 경우, 이 메서드로 기존에 설정된 지역의 특산주를 추천받음
- 사용자 거주지값 갱신 코드 추가
- SuggestServiceTest 테스트 코드 작성
- `memberRepository.findById(memberId)`를 통해 사용자를 조회 후 Mock 데이터로 사용자 존재 확인
- `regionRepository.findAll()`을 통해 모든 지역 가져오고, latitude와 longitude 값을 이용해 가장 가까운 지역을 찾아냄
- `drinkRepository.findByRegion(Region region)`을 통해 해당 지역의 특산주 리스트에서 무작위로 …
=> feat: 사용자 위치 기반 특산주 추천 기능 추가

src/main/java/com/onedrinktoday/backend/domain/comment/service/CommentService.java, src/test/java/com/onedrinktoday/backend/domain/comment/service/CommentServiceTest.java
- CommentService: 회원이 작성한 게시글에 게시글을 작성한 본인이 댓글을 작성하면 알림이 전송되지 않게 하였습니다.
- CommentServiceTest
- 댓글 생성 성공
- `commentRepository.save(eq(comment))`를 통해 정확한 객체가 저장되는지 확인했습니다.
- `argThat`을 사용하여 전달된 댓글의 속성이 예상한 값과 일치하는지 체크했습니다.
- 댓글 수정 성공
- 댓글 객체의 내용을 업데이트한 후 `commentRepository.save(eq(comment))`를 통해 수정된 댓글이 저장되는지 확인했습니다.
- `comment.setContent(newContent)`와 `comment.setAnonymous(isAnonymous)`로 수정된 값을 설정하였습니다.
=> refactor: 댓글 기능 수정과 서비스 로직 수정에 따른 테스트 코드 수정

src/test/java/com/onedrinktoday/backend/domain/manager/service/ManagerServiceTest.java
- 신고 승인에 필요한 URI와 ID 값을 주입하기 위해 `ManagerService`의 `postUri`와 `postId `필드를 설정하였습니다.
- `ReflectionTestUtils.setField(managerService, "postUri", "/posts/{postId}");`
- `ReflectionTestUtils.setField(managerService, "postId", "postId");`
- 기존 테스트 코드 오류를 해결하고 `any()`를 사용하는 대신 `eq()`를 사용하여 명시적으로 비교했습니다. 
- **신고 승인 성공 테스트**
- 신고 객체와 포스트 객체를 찾고, 승인 알림을 보내며, 신고를 저장할 때 승인 상태를 `true`로 설정합니다.
- 승인 후 반환된 응답의 ID와 승인 상태를 확인하였습니다.
- **신고 반려 성공 테스트**
- 신고 반려 요청을 생성하고, 승인된 신고를 반환하도록 설정합니다.
- 반려 후 반환된 응답의 ID와 승인 상태가 `false`인지 확인하였습니다.
=> test: 매니저 테스트 코드 수정

src/test/java/com/onedrinktoday/backend/domain/registration/service/RegistrationServiceTest.java
- **기존 코드에서 발생하던 오류**
- `regionRepository.findById(null)` 호출 시 `findById(0L)`로 잘못된 인자를 전달하여` Strict stubbing argument mismatch` 오류가 발생했습니다.
- 오류 해결을 위해 `RegistrationRequest`에서 `regionId(1L)`을 명시해줌으로써 `findById(null)` 대신 `findById(1L)`로 올바르게 호출되도록 수정하였습니다.
- `findById(anyLong())`를 `findById(eq(1L)`로 변경하여 1L이라는 특정 ID로 findById()가 호출되는 상황을 테스트하는 방식으로 개선하였습니다.
- `registrationRepository.save(any(Registration.class))` 호출 시 `any()`를 사용하던 부분을 `ArgumentCaptor`로 변경하여 `Registration` 객체를 캡처하고 검증하도록 수정했습니다.
- 캡처한 `Registration`객체의 `drinkName`을 검증하도록 추가했습니다.
=> test: 특산주 서비스 테스트 수정
